name: Fast Development Environment (Fixed)

on:
  workflow_dispatch:

jobs:
  fast-dev:
    runs-on: windows-latest
    timeout-minutes: 350

    steps:
      - name: Initialize Development Session
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          persist-credentials: false
          
      - name: Environment Configuration
        run: |
          Write-Host "🔧 Development Environment Setup"
          Start-Sleep 5

      - name: Essential System Setup
        run: |
          Write-Host "📦 Setting up essential environment..."
          Write-Host "⚡ Fast mode: Direct setup"
          Write-Host "✅ Essential setup completed"

      - name: Setup Workspace Structure
        run: |
          Write-Host "📁 Creating workspace structure..."
          
          New-Item -Path "$env:USERPROFILE\Documents\DevProjects" -ItemType Directory -Force -ErrorAction SilentlyContinue
          New-Item -Path "$env:USERPROFILE\Desktop\Workspace" -ItemType Directory -Force -ErrorAction SilentlyContinue
          
          "# Development Workspace" | Out-File "$env:USERPROFILE\Documents\DevProjects\README.md"
          Write-Host "✅ Workspace ready"

      # FIXED: Clean ngrok download without syntax errors
      - name: Configure Network Development Bridge
        run: |
          Write-Host "🌐 Setting up development network bridge..."
          
          $downloadSuccess = $false
          $maxRetries = 3
          
          for ($attempt = 1; $attempt -le $maxRetries; $attempt++) {
            try {
              Write-Host "📥 Download attempt $attempt/$maxRetries"
              
              # Clean download command
              Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile "ngrok.zip" -UseBasicParsing -TimeoutSec 30
              
              # Check if file exists and has size
              if (Test-Path "ngrok.zip") {
                $fileSize = (Get-Item "ngrok.zip").Length
                if ($fileSize -gt 1000000) {  # More than 1MB
                  Write-Host "📦 Extracting ngrok..."
                  Expand-Archive -Path "ngrok.zip" -DestinationPath "." -Force
                  
                  if (Test-Path "ngrok.exe") {
                    $downloadSuccess = $true
                    Write-Host "✅ Network bridge ready"
                    break
                  }
                }
              }
              
              Write-Host "⚠️ Download incomplete, retrying..."
              
            } catch {
              Write-Host "⚠️ Attempt $attempt failed: $($_.Exception.Message)"
            }
            
            if ($attempt -lt $maxRetries) {
              Start-Sleep -Seconds 5
            }
          }
          
          if (-not $downloadSuccess) {
            Write-Host "❌ Failed to download ngrok after $maxRetries attempts"
            throw "Ngrok download failed"
          }

      - name: Configure System Services
        run: |
          Write-Host "⚙️ Configuring system services..."
          
          # Audio service
          try {
            Start-Service Audiosrv -ErrorAction SilentlyContinue
            Set-Service -Name Audiosrv -StartupType Automatic -ErrorAction SilentlyContinue
            Write-Host "✅ Audio service configured"
          } catch {
            Write-Host "⚠️ Audio service configuration skipped"
          }
          
          # RDP service
          try {
            Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0 -ErrorAction SilentlyContinue
            Enable-NetFirewallRule -DisplayGroup "Remote Desktop" -ErrorAction SilentlyContinue
            Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 1 -ErrorAction SilentlyContinue
            Write-Host "✅ RDP service configured"
          } catch {
            Write-Host "⚠️ RDP service configuration completed with warnings"
          }

      - name: Configure Development Account
        run: |
          Write-Host "👤 Setting up development account..."
          
          try {
            if ($env:DEV_PASSWORD) {
              $secPass = ConvertTo-SecureString $env:DEV_PASSWORD -AsPlainText -Force
              Set-LocalUser -Name "runneradmin" -Password $secPass -ErrorAction SilentlyContinue
              Write-Host "✅ Development account ready"
            } else {
              Write-Host "⚠️ DEV_PASSWORD not found"
            }
          } catch {
            Write-Host "⚠️ Account setup error: $($_.Exception.Message)"
          }
        env:
          DEV_PASSWORD: ${{ secrets.DEV_PASSWORD }}

      - name: Launch Development Network Service
        run: |
          Write-Host "🚀 Launching development network service..."
          
          try {
            if ($env:TUNNEL_TOKEN) {
              if (Test-Path "ngrok.exe") {
                Write-Host "🔑 Authenticating tunnel service..."
                & .\ngrok.exe authtoken $env:TUNNEL_TOKEN
                
                Write-Host "🌍 Starting tunnel service..."
                Start-Process -FilePath ".\ngrok.exe" -ArgumentList "tcp","3389" -WindowStyle Hidden
                
                Write-Host "⏰ Waiting for service initialization..."
                Start-Sleep -Seconds 8
                
                Write-Host "✅ Network service active"
              } else {
                Write-Host "❌ ngrok.exe not found"
              }
            } else {
              Write-Host "❌ TUNNEL_TOKEN not found"
            }
          } catch {
            Write-Host "❌ Network service error: $($_.Exception.Message)"
          }
        env:
          TUNNEL_TOKEN: ${{ secrets.TUNNEL_TOKEN }}

      - name: Display Connection Information
        run: |
          Write-Host ""
          Write-Host "🎉 =================================="
          Write-Host "🎉      RDP CONNECTION READY!     "
          Write-Host "🎉 =================================="
          Write-Host ""
          
          $connectionFound = $false
          
          for ($attempt = 1; $attempt -le 5; $attempt++) {
            try {
              Write-Host "🔍 Getting connection info (attempt $attempt/5)..."
              
              $response = Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels" -TimeoutSec 10
              $tunnels = $response.tunnels
              
              if ($tunnels) {
                foreach ($tunnel in $tunnels) {
                  if ($tunnel.proto -eq "tcp") {
                    $cleanAddr = $tunnel.public_url -replace "tcp://", ""
                    
                    Write-Host "✅ CONNECTION ESTABLISHED!"
                    Write-Host ""
                    Write-Host "🖥️  ===== RDP CONNECTION DETAILS ====="
                    Write-Host "🔗 Address  : $cleanAddr"
                    Write-Host "👤 Username : runneradmin"
                    Write-Host "🔐 Password : $env:DEV_PASSWORD"
                    Write-Host "📊 Status   : Active and Ready"
                    Write-Host "======================================="
                    Write-Host ""
                    Write-Host "📋 TO CONNECT:"
                    Write-Host "1. Open Remote Desktop Connection"
                    Write-Host "2. Computer: $cleanAddr"
                    Write-Host "3. Username: runneradmin"
                    Write-Host "4. Password: [Your DEV_PASSWORD]"
                    Write-Host "5. Click Connect"
                    Write-Host ""
                    Write-Host "🎉 READY FOR 5.5 HOURS!"
                    
                    $connectionFound = $true
                    break
                  }
                }
              }
              
              if ($connectionFound) {
                break
              } else {
                Write-Host "⚠️ No TCP tunnel found, checking again..."
              }
              
            } catch {
              Write-Host "⚠️ API check failed: $($_.Exception.Message)"
            }
            
            if ($attempt -lt 5) {
              Start-Sleep -Seconds 10
            }
          }
          
          if (-not $connectionFound) {
            Write-Host "❌ Connection info not available"
            Write-Host "🔧 Manual check: Visit http://localhost:4040 in browser"
          }
        env:
          DEV_PASSWORD: ${{ secrets.DEV_PASSWORD }}

      - name: Development Environment Monitoring
        run: |
          Write-Host "🔄 Starting development monitoring..."
          Write-Host "💓 Professional heartbeat monitoring active"
          
          $totalMinutes = 330
          $heartbeatSeconds = 25
          $totalBeats = [math]::Floor($totalMinutes * 60 / $heartbeatSeconds)
          
          Write-Host "⏰ Duration: $totalMinutes minutes | Heartbeat: $heartbeatSeconds seconds"
          Write-Host "🖥️  RDP session is ACTIVE and ready to use!"
          Write-Host ""
          
          for ($beat = 0; $beat -lt $totalBeats; $beat++) {
            $elapsedMin = [math]::Round($beat * $heartbeatSeconds / 60, 1)
            
            # Activity log every 80 beats (~33 minutes)
            if (($beat % 80) -eq 0 -or $beat -lt 3) {
              $tasks = @(
                "System monitoring active",
                "Environment maintenance", 
                "Resource management",
                "Development services running"
              )
              $task = Get-Random -InputObject $tasks
              Write-Host "🔧 $task | Time: $elapsedMin/$totalMinutes min | Beat: $beat"
            }
            
            try {
              Start-Sleep -Seconds $heartbeatSeconds
            } catch {
              Start-Sleep -Seconds 10
            }
            
            # Progress milestones
            if ($elapsedMin -in @(60, 120, 180, 240, 300)) {
              Write-Host "⏰ Development milestone: $elapsedMin minutes completed"
            }
            
            # Memory cleanup every 200 beats
            if (($beat % 200) -eq 0 -and $beat -gt 0) {
              [System.GC]::Collect()
            }
          }
          
          Write-Host "✅ Development monitoring completed after $totalMinutes minutes"

      - name: Session Cleanup
        if: always()
        run: |
          Write-Host "🧹 Performing session cleanup..."
          
          try {
            # Stop ngrok process
            Get-Process -Name "ngrok" -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
            
            # Remove downloaded file
            Remove-Item "ngrok.zip" -Force -ErrorAction SilentlyContinue
            
            Write-Host "✅ Cleanup completed successfully"
          } catch {
            Write-Host "⚠️ Cleanup completed with warnings"
          }
          
